services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ofx-converter-web
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - SERVICE_URL_WEB_3000
